import assert from 'node:assert/strict';
import {saveSnapshot} from '../src/saveSnapshot.ts';
const tab = {path: 'a.md', name: 'a.md', dirty: true};
assert.equal(await saveSnapshot(tab, 'a', async () => null, () => 'a'), false);
assert.equal(tab.dirty, true);
assert.equal(tab.path, 'a.md');
await assert.rejects(saveSnapshot(tab, 'a', async () => {throw new Error('disk full');}, () => 'a'));
assert.equal(tab.dirty, true);
let finish;
let content = 'a';
const other = {path: 'b.md', name: 'b.md', dirty: true};
const pending = saveSnapshot(tab, content, () => new Promise(resolve => {finish = resolve;}), () => content);
content = 'a plus edits';
finish('renamed.md');
assert.equal(await pending, true);
assert.equal(tab.dirty, true);
assert.equal(tab.path, 'renamed.md');
assert.deepEqual(other, {path: 'b.md', name: 'b.md', dirty: true});
await saveSnapshot(tab, content, async () => 'renamed.md', () => content);
assert.equal(tab.dirty, false);
console.log('10 de 10 pruebas de guardado asincrono correctas');
